### ISSUE TITLE
Check the existence of a generator regulating the voltage

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynaflow-launcher#114]
@marcochiaramello @cossartque I would be in favor of adding such a check in the launcher. What is your opinion?

**Comment by cossartque** [comment]
I think there is no reason to simulate a network with no generator regulating the voltage so yes, I agree.

**Comment by marcochiaramello** [comment]
Agreed.

**Comment by lecourtoisflo** [comment]
Finally, we'll implement the check at least one connected generator in voltage regulation on in the main connex component
