### ISSUE TITLE
adapt CMAKE scripts for older cmake versions

### ISSUE THREAD

**Issue by marcochiaramello** [dynawo/dynaflow-launcher#161]
-b option does not exists for older version of cmake (e.g. cmake 3.12). This prevents build.

**Comment by lecourtoisflo** [comment]
Seems irrelevant to me because cmake 3.12 is required to compile dynawo with c++11 enabled (3rd parties) and DFL requires c++11 dynawo

**Comment by marcochiaramello** [comment]
it is relevant because option -b does not exist in cmake 3.12, but only for later versions
