### ISSUE TITLE
Proceed to a review of all the options in the config.json

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynaflow-launcher#217]
SVCRegulationOn : when true keep implementing what is implemented today (SVarCPV), when false do not put any SVarC model in the dyd.

ShuntRegulationOn : when false do not implement SMACC/ACMC, nor the centralized shunt regulation (nothing in dyd for shunts)

AutomaticSlackBusOn : if true search for slack bus in iidm extension

@marcochiaramello fyi

**Comment by lecourtoisflo** [comment]
Filter SMAC/ACMC by not taking into account shunt associations in assembling/settings files

**Comment by rosiereflo** [comment]
see branch 217_options

**Comment by marcochiaramello** [comment]
> see branch 217_options

a new branch is going to be created as many things has changed in meanwhile
