### ISSUE TITLE
Unable to run dynawo after dynaflow launcher

### ISSUE THREAD

**Issue by jlbouchot** [dynawo/dynaflow-launcher#447]
Running Dynaflow launcher in debug mode generates a .job file which is causing dynawo to crash when ran afterwards. 

Commenting the <dyn:lostEquipments/> tag seems to solve the issue in dynawo and it may be misplaced in the .job generation file.

**Comment by rosiereflo** [comment]
Coulc you please provide a testcase or the faulty .jobs file? I was not able to reproduce this

**Comment by rosiereflo** [comment]
Solved on latest master version
