### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynaflow-launcher#467]
The following unit tests fail :
7 - INPUTS.TestConfig (Failed)
10 - OUTPUTS.TestJob (Failed)

**Comment by rosiereflo** [comment]
I am not able to reproduce on master and all nightly passes?

**Comment by cossartque** [comment]
> I am not able to reproduce on master and all nightly passes?

Then it might be a pb on my side, I close the issue
