### ISSUE TITLE
Probleme when getting season from a tfo

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynaflow-launcher#559]
The following single association : 
  singleAssociation id="MESURE_I_ADA_PRAGNL61DEPHG"
    tfo name="PRAGNL61DEPHG"
  singleAssociation

with the following setting:
    ref id="MESURE_I_ADA_PRAGNL61DEPHG" name="currentLimitAutomaton_Season" tag="@SAISON@" type="STRING"

gives the following error:
settings ref currentLimitAutomaton_Season references the single association MESURE_I_ADA_PRAGNL61DEPHG which is not associated to a line: it will be ignored

**Comment by rosiereflo** [comment]
Please use @SEASON@ (capitals)

**Comment by rosiereflo** [comment]
OK, please ignore my previous message as it seems it's github that remove the capitals. Would you have a testcase?
