### ISSUE TITLE
"connectable bus is not set" issue

### ISSUE THREAD

**Issue by geofjamg** [dynawo/dynaflow-launcher#697]
Hi,

When running dynaflow on an IIDM file exported from the bus view topology I get the following error message:
```bash
Simulation failed: error while parsing file network.xiidm : Shunt compensator 'AAAA': connectable bus is not set ( DYNDataInterfaceIIDM.cpp:139 )
```
IIDM C++ implementation seems to require the "connectableBus" attribute which is a wrong interpretation of the IIDM topology model.
It is sometimes impossible not only the have a valid "bus" but also a "connectableBus". For instance in a node/breaker voltage when you open all the switches. You don't have any bus in the bus view (and also in the bus/breaker view) and so on you are not able to define a valid "connectableBus".

**Comment by rosiereflo** [comment]
Hi, could you please open this issue on the powsybl-iidm4cpp github? DFL project is just an user of this library. Thanks
