### ISSUE TITLE
[iidm 1.2] use of generator with line impedence model

### ISSUE THREAD

**Issue by marcochiaramello** [dynawo/dynaflow-launcher#80]
When multiple generators (in voltage regulation) are attached to two nodes connected via a retained switch, the generator with line impedence model should be used to avoid twice the same equation in the system

**Comment by cossartque** [comment]
@marcochiaramello @PerninGuillaume we should keep in mind that the same will apply with the distant voltage regulation when two generators control the voltage at two nodes connected via a retained switch. In that case we should use the GeneratorPQProp model (and the VRRemote model).
