### ISSUE TITLE
Use the simple cpp generator model when targetP < pMin or targetP > pMax

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynaflow-launcher#84]
We have seen cases in examples where in the iidm targetP (or p) is lower than pMin or higher than pMax.
In that case we should not implement a generator model in the .dyd file but do nothing and let dynawo use a simple injector cpp model.
@marcochiaramello what do you think ?

**Comment by marcochiaramello** [comment]
I agree with your proposition. What about cases where targetP = 0 (inside generator diagram) and voltage regulation is on? If we let those cases participating to active power mismatch resorption is like we are turning them up, no?

**Comment by cossartque** [comment]
I agree too, those generators shouldn't participate in the active power regulation.
As they still participate in the voltage regulation, we have to use a Modelica model in the .dyd and cannot simply use the cpp model.
I would suggest that in that case we put KGover to 0 (this is what is done in DynaWaltz for generators that don't participate).

**Comment by cossartque** [comment]
The case of generators where targetP = 0 (inside generator diagram) should be handled in another issue I think.

**Comment by adriguir** [comment]
> The case of generators where targetP = 0 (inside generator diagram) should be handled in another issue I think.

Yes, please open a new issue so that we have it in mind.

**Comment by cossartque** [comment]
> > The case of generators where targetP = 0 (inside generator diagram) should be handled in another issue I think.
> 
> Yes, please open a new issue so that we have it in mind.

Ok, done
