### ISSUE TITLE
Change the load parameters in the Network.par

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynaflow-launcher#85]
The following parameters should be updated :
    par type="DOUBLE" name="load_Tp" value="10"
    par type="DOUBLE" name="load_Tq" value="10"
    par type="DOUBLE" name="load_alpha" value="1.5"
    par type="DOUBLE" name="load_beta" value="2.5"
    par type="BOOL" name="load_isRestorative" value="true"
This way we use the same restorative load model in cpp and in Modelica (except for the limits).

**Comment by marcochiaramello** [comment]
agreed, but then how do we keep load below DSOThreshold purely alpha beta? In my opinion, we have to specify in network, for each of those cases, something like:
par type="BOOL" name="loadName_isRestorative" value="false"

**Comment by cossartque** [comment]
If we still use this DSOThreshold to use .mo models (for high voltage) or cpp models (for low voltage) then the cpp models will be only alpha beta loads and we should have isRestorative = false. Anyway, we still need to modify alpha and beta that are equal to zero in the current version (purely PQ load).

**Comment by cossartque** [comment]
I think the question here is : what is the default cpp model that we should use if we don't specify for each cpp load ?
Is it Alpha-Beta restorative ? Is it pure Alpha-Beta ? Is it PQ ?
For the moment it is PQ (not restorative and alpha = beta = 0) in DFL, I don't know if it is the best choice.
@marcochiaramello and @adriguir what do you think ?

**Comment by adriguir** [comment]
For performance reasons, I think the final choice will be to enrich the Cpp model to have potential limits in its restorative version and to either use an alpha-beta restorative load with limits model (Cpp) for loads above dsoThreshold and a pure alpha-beta load model (Cpp) for loads below the threshold.

IHMO, the default will be to have a restorative load with limits model (as in most of the cases and in particular in French test cases, LV won't be represented). 

The proper way to deal with this issue in DFL is to use the possibility to change the behavior for a certain number of specific loads in the network par, getting this final structure:

par type="DOUBLE" name="load_Tp" value="10"
par type="DOUBLE" name="load_Tq" value="10"
par type="DOUBLE" name="load_alpha" value="1.5"
par type="DOUBLE" name="load_beta" value="2.5"
par type="BOOL" name="load_isRestorative" value="true"

which is default and if any load below dsoThreshold enriched in the following way:
par type="DOUBLE" name="load_Tp" value="10"
par type="DOUBLE" name="load_Tq" value="10"
par type="DOUBLE" name="load_alpha" value="1.5"
par type="DOUBLE" name="load_beta" value="2.5"
par type="BOOL" name="load_isRestorative" value="true"
par type="BOOL" name="loadABelowThreshold_isRestorative" value="false" // overwrite the previous generic setting

I consider it would be necessary to address this quite soon, both in dynawo core and in DFL.

**Comment by cossartque** [comment]
In your proposal, is the line 
par type="BOOL" name="loadABelowThreshold_isRestorative" value="false" // overwrite the previous generic setting
common to all the loads below the voltage threshold (and therefore the threshold parameter should be known in dynawo core) or should we have one line for each concerned load ?

**Comment by adriguir** [comment]
In the current state of dynawo core, no: you have to specify the specific behavior for each load so you would have one line for each concerned load. It of course opens questions because it can take time to read the parameters. We can also imagine adding a new generic parameter that will be quite the equivalent of the dsoThreshold into the core but I'm not really in favor of this option (being perhaps too specific to one vision of the world).

In addition, I hope that sooner or later, especially for contingency analysis, we will be able not to parse the input files for each contingency.

**Comment by cossartque** [comment]
I am also not very fond of the solution with an additional parameter in dynawo as it is very DynaFlow oriented.
