### ISSUE TITLE
Fix the dyd.cpp and the par.cpp for HVDC

### ISSUE THREAD

**Issue by cossartque** [dynawo/dynaflow-launcher#97]
When both converters are in the main cc nothing should be written in the dyd.cpp and in the par.cpp for the moment.
It is not the case in the current version.
A test showed that :
- In the .dyd we have a line that implements HvdcPVDangling or HvdcPTanPhiDangling even when both converters are in the main cc, which should not be the case (normally we should not have anything in the .dyd for the moment).
- In the .par we have parameters for an HVDC with both converters in the main cc, which should not be the case.
@marcochiaramello fyi

**Comment by marcochiaramello** [comment]
can we add a test on this specific case?
Thanks

**Comment by cossartque** [comment]
Yes, we can add the 12nDynaFlow.iidm that I sent to @PerninGuillaume to the main tests
